### ISSUE TITLE
Asterisk13 package misssing bridge modules

### ISSUE THREAD

**Issue by Hobb** [openwrt/telephony#34]
Package Asterisk 13.2.0 looks like is missing the necessary bridge modules (e.g. simple_bridge.so should be in /usr/lib/asterisk/modules).

They do not appear amongst the modules in the current makefile (not sure if not built or not copied though).

**Comment by jslachta** [comment]
The bridge modules are missing because of the initial release of OpenWrt package. I tried to deliver at least something instead of nothing. Bridge modules are on its way, several modules has been changed, several modules has been removed and several has been replaced. With the upcoming update (within several days) there are going to be more modules, I hope bridge modules will get in there too.

**Comment by Hobb** [comment]
Ah, okay, I can at least confirm you that everything else I tried up to that point worked flawlesly (registration with external SIP, registration of client SIPS and emission and reception of phone calls).

Thanks for your work ;)

**Comment by jslachta** [comment]
Should be fixed. Bridge modules are as a part of app-confbridge module.
