### ISSUE TITLE
freeswitch master branch build issue

### ISSUE THREAD

**Issue by seven1240** [openwrt/telephony#345]
First thanks a lot to get FreeSWITCH working in OpenWrt.

Maintainer: 
Mazi Lo <openwrt.forum.mazilo@recursor.net>
micmac1 <sebastian_ml@gmx.net>

Environment: (put here arch, model, OpenWRT/LEDE version)

macOS: target x64_64
openwrt: 5c5bf8b8658a588423f6ec445d7ef6a36f99a396 2018-01-19 14:45 Adrian Schmutzler                 o [master] {origin/master} {origin/HEAD} ar71xx: Add support for TP-Link CPE210 v2
telephony: c7cb1e30c2170a44639be04005f938b7322cb4df 2018-06-21 21:14 micmac1                                 M─┐ {origin/master} {origin/HEAD} Merge pull request #339 from micmac1/fs-pcre

Description:

I'm a FreeSWITCH Developer and trying to get the master branch working. I successfully built the freeswitch-stable project, but now the freeswitch one.

1) freeswitch not showing in make menuconfig

How to make it show in menuconfig?

2) by disable hiredis and erlang, seems I can successfully build that, but not seeing any package. but seems not ipk generaed in bin/ , the build command was:

```
make package/freeswitch/compile V=s
```

Thanks,
Seven.

**Comment by micmac1** [comment]
Hello Seven,

the master branch package isn't really maintained. I don't know why it doesn't show up in menuconfig and even if it did I think it wouldn't compile.

Kind regards,
Seb

**Comment by seven1240** [comment]
hi Seb,

I'm happy to see the merge or OpenWrt/LEDE that means I can contribute to a single place.

I don't know how to become a maintainer, but if someone helps me get it compiled I can check regularly to make it work.

The stable branch works so the master branch should be now that hard. Just I'm new to OpenWrt so need some help.

Thanks,
Seven.

**Comment by micmac1** [comment]
Hi Seven,

It seems when you delete "+SSP_SUPPORT:libssp" from freeswitch/Makefile
then it shows up in menuconfig.

You could send pull requests to Mazi, but I'm not sure how regularly he
checks this.

Best of luck,
Seb

**Comment by seven1240** [comment]
with some manual hacks I can get this far

```
libtool: Version mismatch error.  This is libtool 2.4.6, but the
libtool: definition of this LT_INIT comes from libtool 2.4.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
libtool: and run autoconf again.
make[6]: *** [xmlparse.lo] Error 63
```

that's from FreeSWITCH embeded `apr-util`. 

the problem seems we have multi version of libtool. 

```
./build_dir/host/libtool-2.4/libtool --version
libtool (GNU libtool) 2.4

./staging_dir/host/bin/libtool --version
libtool (GNU libtool) 2.4
```

```
./staging_dir/target-x86_64_musl//host/libltdl/bin/libtool --version
libtool (GNU libtool) 2.4.6
```

```
build_dir/target-x86_64_musl/freeswitch-1.9.0/libs/apr-util//xml/expat/libtool --version
libtool (GNU libtool) 2.4.6
```

I already have FIXUP in Makefile

```
PKG_FIXUP:=autoreconf
```

so question is what's the proper way to solve the miss match? If there's more information needed to trace this I can provide more and push my patch to a branch to test.

Thanks.

**Comment by cotequeiroz** [comment]
I've done some more compile-testing here.  

MySQL support was apparently removed by upstream.

The mysql file presence check fails when cross-compiling and for mips, the package attempts to set it to no.  However, this does not work because variables are not passed down to other instances of `configure`.  I've fixed this by adding it to `CONFIGURE_ARGS` unconditionally, so there's no need to patch `libs/apr-util/configure.ac` like I've done before.

`libs/apr-util/INSTALL.MySQL` states "The MySQL driver is not distributed from apache.org due to licensing issues. If you wish to build the driver, download `apr_dbd_mysql.c` from
http://apache.webthing.com/database/ and copy it into the dbd directory."

Even after adding the right file, it would not work because the generation of build-outputs.mk was commented, so the downloaded file will not be compiled.  I'm not going to second-guess their reason, so instead of removing the comment and hope for the best, I have dropped the mysql option.

The patch files are the same across the C libraries, so I've cleaned that up as well. 
Finally, I've updated the auxiliary files download procedure.

I don't use the package--I don't even know how to configure it--to run-test it.  I'm updating my branch to what I think should be right.

@micmac1, what do you think, should I go ahead and open a PR to try to fix this, or am I in over my head proposing wholesale changes?

@seven1240, have you had a chance to try it?

Cheers,

**Comment by jslachta** [comment]
FreeSWITCH package was moved to packages-abandoned repository. All FS users should use freeswitch-stable package. I consider this issue fixed.
