### ISSUE TITLE
asterisk-16 support. 

### ISSUE THREAD

**Issue by dmsherazi** [openwrt/telephony#410]
There is a bug in asterisks [#821392 Astersk take exclusive control of audio device](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821392)
 which is fixed in Asterisk-16.

**Comment by micmac1** [comment]
Hello Dost,

That bug report is from 2016. Asterisk 16 was far from being released at that time.

I saw your forum post where you wrote you have problems with chan_alsa, https://forum.openwrt.org/t/asterisks-locks-alsa-device-if-chan-alsa-is-loaded/32006. I think what you probably need to do is figure out a way to set up a software mixing device (didn't fiddle with that in a long time but I think you do that with dmix) and then configure chan_alsa (and mpd) to use that instead of hw:0,0. I don't think there is an actual bug in chan_alsa.

On another note, I'm working on a pull request to update asterisk 15 to 16. So if it all works out and if Jiri agrees to it you might have packages for 16 in trunk shortly.

Kind regards,
Seb

**Comment by dmsherazi** [comment]
@micmac1 Thanks for pointing out the solution. Using a dmix plugin of alsa as you suggested solves the issue.

**Comment by micmac1** [comment]
Hi Dost,

Glad you got it to work. Have a nice day!

Best regards,
Seb
