### ISSUE TITLE
Add CircleCI or any other CI

### ISSUE THREAD

**Issue by BKPepe** [openwrt/telephony#442]
I think it will be really useful if there CircleCI or any other CI is added to this repository for pull requests. From build logs, we can see that packages are compiled.

CircleCI has a free plan, which should be enough. It is used in openwrt/packages and recently it was added also to openwrt/luci.

**Comment by micmac1** [comment]
In my opinion it would be nice-to-have. But in the last two years I just remember one commit where it would have been useful. There was a pull request for bcg729 which bombed on the buildbots because the commit wasn't actually tested by the user who sent the PR.

The other failures where usually on a certain target, ARC, because of a different toolchain. And it seems even CI from packages doesn't test on that target.

All in all I don't feel strongly about it one way or the other.

**Comment by jslachta** [comment]
@jow- , @hnyman , please, would you be so kind as to authorize CircleCI for this repository?

Please, see https://circleci.com/gh/openwrt/telephony/edit

Thank you.

**Comment by hnyman** [comment]
> would you be so kind as to authorize CircleCI for this repository?

Sorry, I have no experience in making the circleci setup/authorisation.

I think that @thess or @champtar set it up for the packages repo.

**Comment by champtar** [comment]
@jslachta I'll try to have a look
![image](https://user-images.githubusercontent.com/3536755/79380702-c8a98f00-7f2e-11ea-988f-74b3b648af25.png)
I'm not sure why it's asking for private access

**Comment by champtar** [comment]
Sorry for the delay, I enabled CircleCI acces, setup the telephony repo, and disabled CircleCI access again, it should work as it's what we have for packages repo

**Comment by champtar** [comment]
see #521, everything is working (I've also added DCO check)

**Comment by micmac1** [comment]
Hi all,

I rebased and force-pushed to #519 to start CI and the CI run failed:

```
=== Checking commit '5b3ee38f25e5ec063b413af1b66567d332e9319f'
Author name (Sebastian Kemper) seems ok
Commit subject line MUST start with '<package name>: ' (kamailio-5.x: add app_python3)
Signed-off-by match author
=== Checking commit 'bc25c23a929e1835764dffdbba7792e3ba6990fe'
Author name (Sebastian Kemper) seems ok
Commit subject line MUST start with '<package name>: ' (kamailio-5.x: update build setup)
Signed-off-by match author

Exited with code exit status 1
```

The problem is the dot in the package name. We'd have the same problem with asterisk-16.x.

```
sk@darth ~/github/telephony $ echo "kamailio-5.x: update build setup" | grep -q -e '^[0-9A-Za-z,+/_-]\+: ' -e '^Revert '
sk@darth ~/github/telephony $ echo $?
1
```

I know of only one restriction regarding the package name: do not include underscores. And that I find also written here: [link](https://openwrt.org/docs/guide-developer/packages):

> PKG_NAME - The name of the package, as seen via menuconfig and ipkg. Avoid using underscores in the package name, to avoid build failures–for example, the underscore separates name from version information, and may confuse the buildsystem in hard-to-spot places.

So kamailio-5.x seems legit. I think we should update the regex to allow this schema. If we went the other way and renamed the packages that would create some confusion (apart from possible mistakes/oversights while renaming). I don't see the need in that.

I think we can just add the dot into the regex's character class and be done with it:

```
sk@darth ~/github/telephony $ echo "kamailio-5.x: update build setup" | grep -q -e '^[0-9A-Za-z,.+/_-]\+: ' -e '^Revert '
sk@darth ~/github/telephony $ echo $?
0
sk@darth ~/github/telephony $
```

Any thoughts?

Kind regards,
Seb

**Comment by micmac1** [comment]
I just realized the PKG_NAMEs are actually kamailio5 and asterisk16. I think we're just so used to use the directory name in the subject.

So either we update our habit or we relax the regex a bit. Which will it be? :)

**Comment by jslachta** [comment]
We should update the regex.

**Comment by micmac1** [comment]
>We should update the regex. 

OK :-D

**Comment by micmac1** [comment]
Hello @BKPepe and @champtar 

Thanks for setting this up and helping us out!

**Comment by jslachta** [comment]
I'm sending my thanks to all of you. This repository took one step further.
