### ISSUE TITLE
baresip: upgrade to version 0.6.4

### ISSUE THREAD

**Issue by alfredh** [openwrt/telephony#474]
Hi,

is it possible to upgrade baresip to latest release?

https://github.com/alfredh/baresip/releases

Br, Alfred

**Comment by micmac1** [comment]
Hi Alfred, I'll take care of it.

**Comment by alfredh** [comment]
@micmac1 thanks alot, very much appreciated :)

**Comment by ggrandis** [comment]
Thank you very much @micmac1

**Comment by micmac1** [comment]
Am October 12, 2019 3:11:10 PM UTC schrieb "Alfred E. Heggestad" <notifications@github.com>:
>@micmac1 thanks alot, very much appreciated :)

Do you want the patch from  https://github.com/alfredh/baresip/issues/811#issuecomment-541328239 included?

**Comment by ggrandis** [comment]
Yes, please ;)Giordano
-------- Messaggio originale --------Da: micmac1 <notifications@github.com> Data: 12/10/19  19:57  (GMT+01:00) A: openwrt/telephony <telephony@noreply.github.com> Cc: ggrandis <g.grandis@invidea.it>, Comment <comment@noreply.github.com> Oggetto: Re: [openwrt/telephony] baresip: upgrade to version 0.6.4 (#474) Am October 12, 2019 3:11:10 PM UTC schrieb "Alfred E. Heggestad" <notifications@github.com>:
>@micmac1 thanks alot, very much appreciated :)

Do you want the patch from  https://github.com/alfredh/baresip/issues/811#issuecomment-541328239 included?


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openwrt/telephony/issues/474?email_source=notifications\u0026email_token=AJDSC3E3RATUDNXGEDXQ3KDQOIFXFA5CNFSM4JADEX7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBCE6SQ#issuecomment-541347658",
"url": "https://github.com/openwrt/telephony/issues/474?email_source=notifications\u0026email_token=AJDSC3E3RATUDNXGEDXQ3KDQOIFXFA5CNFSM4JADEX7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBCE6SQ#issuecomment-541347658",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alfredh** [comment]
no the patch is not tested.

vanilla baresip is best.

**Comment by micmac1** [comment]
OK, will remove tonight.

**Comment by micmac1** [comment]
Hi @ggrandis 

Beware the update is for OpenWrt trunk. CC (Chaos Calmer) is end of life. And all current releases will likely not get the update to baresip 0.6.4. Also please consider: the modules depending on ffmpeg aren't built by default, because ffmpeg often fails to compile, so defaulting to include ffmpeg support would lead to baresip to fail as well (due to packaging wouldl).

So if you want video (and the extra patch) you'll need to compile yourself. You could try a snapshot for your target device, then download the SDK and build baresip.

Regards,
Seb
