### ISSUE TITLE
asterisk: Unable to open key directory '/usr/share/asterisk/keys'

### ISSUE THREAD

**Issue by 532910** [openwrt/telephony#512]
Maintainer: @jslachta
Environment: 19.07.2 /  sunxi / cortexa53 / sun50i-h5-nanopi-neo2
Description:
`CLI> core restart now` gives this warning:

```
WARNING: res_crypto.c:513 crypto_load: Unable to open key directory '/usr/share/asterisk/keys'
```

and it's true, the directory doesn't exist:
```
# ls /usr/share/asterisk/keys
ls: /usr/share/asterisk/keys: No such file or directory
```

It should be:
```
# ls /var/lib/asterisk/keys
```

And it's specified in my `asterisk.conf`:
```
# grep key /etc/asterisk/asterisk.conf 
astkeydir => /var/lib/asterisk
```

But looks like it's hardcoded:
```
# strings /usr/sbin/asterisk  | grep asterisk/keys
/usr/share/asterisk/keys
```

As I've found, `/usr/share/asterisk/keys` is specified here:
https://github.com/openwrt/telephony/blob/06ec029b2ff5671610a0862d785b52f0d383420b/net/asterisk-16.x/files/asterisk.conf#L21
https://github.com/openwrt/telephony/blob/06ec029b2ff5671610a0862d785b52f0d383420b/net/asterisk-16.x/files/asterisk.init#L68
but it's unclear how these files are uses.

**Comment by 532910** [comment]
I'm ready to fix, test and PR.

**Comment by micmac1** [comment]
On Wed, Apr 01, 2020 at 05:34:26PM -0700, sergio wrote:
> I'm ready to fix, test and PR.

It's probably a misunderstanding of the configuration. You probably have

[directories](!)
...
astkeydir => /var/lib/asterisk

The "(!)" makes this a template. So if you don't configure the use of
this template then it won't do anything.

**Comment by 532910** [comment]
Ha, yes, I missed it. But anyway it should look into /var/lib/asterisk/keys same as asterisk on debian for example does.

**Comment by micmac1** [comment]
I don't think so. /var is tmpfs on OpenWrt. Why would you want your keys there? They'd be lost during next reboot. You should configure a folder that can survive a reboot.

**Comment by 532910** [comment]
The default configuration MUST work without warnings!

I have no keys, I just want no warnings.

**Comment by 532910** [comment]
Steps to reproduce: install asterisk and `module load res_crypto.so` in the console.

**Comment by micmac1** [comment]
The config and init script you referred to above are from master. They
are different compared to the ones in 19.07. In master
/usr/share/asterisk/keys is the default in /etc/config/asterisk and will
be created if not existing. So in master you shouldn't see this warning.

In 19.07 the old init script is used (non-procd). There
/var/lib/asterisk/keys is hardcoded in the init script.

[ -d $DEST/var/lib/asterisk/keys ] || mkdir -p $DEST/var/lib/asterisk/keys

I don't think warnings are an issue. If you feel strongly about it sent
a pull request for 19.07 to change the hardcoded directory in the init
script.

Personally I don't think that makes much sense, because in the old 19.07
init script the directories are hardcoded and can't be changed via
/etc/default/asterisk. And while this may be be fine for the default
configuration "(!)" this would not create the correct directory if the
user changes the default config in /etc/asterisk. So the user would
usually change the init script to reflect his/her directory of choice
anyway.

The bigger issue in my opinion is that asterisk doesn't allow specifying
directories as command line parameters. But that is neither here nor
there, package maintainers have no say in that, that's upstream
decision.

**Comment by micmac1** [comment]
I thought about this some more. I think the directory in the init script should be the default directory asterisk is using for keys, which is /usr/share/asterisk/keys.

I'll send a pull request to that effect.

**Comment by micmac1** [comment]
Closing, update in 1907. Thanks!
