### ISSUE TITLE
asterisk-chan-dongle "excess" dependencies

### ISSUE THREAD

**Issue by p-velasco** [openwrt/telephony#536]
Maintainer: @micmac1 
Environment: (any)
Description:

The asterisk-chan-dongle package depends on:
```
+kmod-usb-acm +kmod-usb-serial +kmod-usb-serial-option +libusb-1.0 +usb-modeswitch
```

However, being and embedded environment, I consider these dependencies should not be included, as option devices don't need the usb-acm module (and vice versa?), and even then, maybe the user included the driver in kernel? So installing the correct serial driver should be left to the user, the same goes with the other dependencies (I don't know if usb-modeswitch is needed for all modems).

Thank you for your great work

**Comment by micmac1** [comment]
Hello @p-velasco 

Maintainer is @jslachta 

I checked and none of the mentioned depends are hard depend, so the channel plugin doesn't need to be packaged with them. As far I as I can see these depends have been in there since the beginning.

I'll send a pull request to Jiri with an updated dongle and the depends removed, to try it on for size.

Regards,
Seb
